version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies
      - apt-get update -y
      - apt-get install -y nginx
  build:
    commands:
      - echo Building app
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Build complete
artifacts:
  files:
    - /var/www/html/index.html
